### PR TITLE
copy of file, formatting of existing code

### PR DESCRIPTION
**Pull request by Shelleytee**
copied original file and formatted the code with appropriate indentation. Ran validation through W3. Code not corrected at this point. Some role classes un-needed.

### CODE REVIEW

**Comment by andre-charb** [comment]
Hey Shelleytee!  
Couple things:
1. Try to keep your <p> tags like this:
`<p>`
text...
`</p>`

2. Watch out for random white space in paragraphs like the following in your file:
Line 78: "one on this site</a>                    so that"
Line 52: "novices can use them as"

3. Fix the line wrapping and spacing on lines 133-135, 142-143, 153-154, 165-166, 169-170.

Looking good.  Nearly there.

**Comment by andre-charb** [comment]
Looks good.  Just a couple more issues as per below.

See extra line breaks on lines:
121-122
138-139
142-143

Extra spacing on line:
48

**Comment by andre-charb** [comment]
All merged.   ;)

**Comment by Shelleytee** [comment]
Your too on the ball @andre-charb . Thanks for that. I did see all those when our waffle said take 5 mins to have read the code. LOL I went oops. Look at all those things I missed. Have been reading and playing since. Did do another push and now I see that you got there before me. Thanks for that. If I was a multi-millionaire I would so get you to do my stuff. How awesome are you...

**Pull request merged**
